export enum ProviderType {
  PLUMBING = "PLUMBING", //
  CLEANING = "CLEANING",
  BABYSITTING = "BABYSITTING",
  FURNITURE = "FURNITURE", //
  GARDENING = "GARDENING",
  ELECTRICIAN = "ELECTRICIAN", //
  PHOTOGRAPHY = "PHOTOGRAPHY",
  COOKING = "COOKING",
  DRIVING = "DRIVING",
  PAINTING = "PAINTING", //
  CARPENTRY = "CARPENTRY", //
  GUTTER = "GUTTER", //
  SIDING = "SIDING", //
  DELIVERING = "DELIVERING",
  REPAIRS = "REPAIRS", //
}

export enum ProviderLocation {
  SEOUL = "SEOUL",
  BUSAN = "BUSAN",
  INCHEON = "INCHEON",
  DAEGU = "DAEGU",
  GYEONGJU = "GYEONGJU",
  GWANGJU = "GWANGJU",
  CHONJU = "CHONJU",
  DAEJON = "DAEJON",
  JEJU = "JEJU",
}

export enum ProviderStatus {
  PENDING = "PENDING",
  ACTIVE = "ACTIVE",
  SUSPENDED = "SUSPENDED",
  DEACTIVATED = "DEACTIVATED",
  BANNED = "BANNED",
  DELETE = "DELETE",
}

export enum ProviderLevel {
  NEW = "NEW", // 3
  BRONZE = "BRONZE", // 3
  SILVER = "SILVER", // 4
  GOLD = "GOLD", // 5
  PLATINUM = "PLATINUM", // 6
  VERIFIED = "VERIFIED", // 7
}

export enum ProviderWorkWeekday {
  WEEKDAYS = "WEEKDAYS",
  WEEKENDS = "WEEKENDS",
  FULL_WEEK = "FULL_WEEK",
  CUSTOM = "CUSTOM",
}

export enum ProviderWeekday {
  MONDAY = "MONDAY",
  TUESDAY = "TUESDAY",
  WEDNESDAY = "WEDNESDAY",
  THURSDAY = "THURSDAY",
  FRIDAY = "FRIDAY",
  SATURDAY = "SATURDAY",
  SUNDAY = "SUNDAY",
}

export enum ProviderRateType {
  HOURLY = "HOURLY",
  FIXED = "FIXED",
  NEGOTIABLE = "NEGOTIABLE",
}
